# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.120</version>
#    <timestamp>2026-08-15T13:59:33.669Z</timestamp>
#    <hash>4fdd12ca0650a7fc</hash>
# </meta>

forge:
  - "/^forge$/m"
fabric:
  - "/^fabric$/m"
