# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.121</version>
#    <timestamp>2026-09-02T09:33:44.721Z</timestamp>
#    <hash>e00b64f9690b82d1</hash>
# </meta>

forge:
  - "/^forge$/m"
fabric:
  - "/^fabric$/m"

1.21.x:
  - "/^1.21$/m"
1.20.x:
  - "/^1.20$/m"
