# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.120</version>
#    <timestamp>2026-08-15T16:53:42.340Z</timestamp>
#    <hash>fd1cacd887d850db</hash>
# </meta>

neoforge:
  - "/^neoforge$/m"
forge:
  - "/^forge$/m"
fabric:
  - "/^fabric$/m"

1.21.x:
  - "/^1.21$/m"
1.20.x:
  - "/^1.20$/m"
