name = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1e0296c1a9f7bc28fcd76781e19681aaaea40e70464cebfdde007062fd4e0bf"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
