# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
mod_id=thigh_highs_etc
mod_name=Thigh highs etc
mod_author=possible_triangle
mod_version=0.0.0-dev
mod_description=addon for etcetera adding thigh highs
release_type=release

# Common
mc_version=1.20.1

# Forge
forge_version=47.4.22

# Fabric
fabric_api_version=0.92.11+1.20.1
fabric_loader_version=0.19.3

# Publishing
repository=teamgalena/thighhighsetc
maven_group=dev.galena
curseforge_project_id=905853
modrinth_project_id=6aZTHLYT
