[versions]
galena-hats = "1.3.1"
jei = "19.44.0.401"
dye-depot = "1.21.1-2.1.1"

[libraries]
neoforge-stub = { group = "com.possible-triangle", name = "neoforge_stub", version = "1.0.10" }

registrate-neoforge = { module = "com.tterrag.registrate:Registrate", version = "MC1.21-1.3.0+67" }
registrate-fabric = { module = "com.tterrag.registrate_fabric:Registrate", version = "1.3.6-MC1.21.1" }

jei-neoforge = { group = "mezz.jei", name = "jei-1.21.1-neoforge", version.ref = "jei" }
jei-fabric = { group = "mezz.jei", name = "jei-1.21.1-fabric", version.ref = "jei" }

dye-depot-neoforge = { group = "com.ninni.dye_depot", name = "dye_depot-neoforge", version.ref = "dye-depot" }
dye-depot-fabric = { group = "com.ninni.dye_depot", name = "dye_depot-fabric", version.ref = "dye-depot" }

galena-hats-neoforge = { module = "dev.galena:hats-1.21.1-neoforge", version.ref = "galena-hats" }
galena-hats-fabric = { module = "dev.galena:hats-1.21.1-fabric", version.ref = "galena-hats" }

yacl-neoforge = { module = "dev.isxander:yet-another-config-lib", version = "3.8.2+1.21.1-neoforge" }
yacl-fabric = { module = "dev.isxander:yet-another-config-lib", version = "3.8.2+1.21.1-fabric" }
