modLoader="javafml"
loaderVersion="[1,)"
license = 'https://github.com/${repository}/blob/1.21.x/LICENSE.md'
issueTrackerURL = "https://github.com/${repository}/issues"
showAsResourcePack = false
updateJSONURL = "https://api.modrinth.com/updates/thigh-highs-etc/forge_updates.json?neoforge=only"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = "${mod_description}"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    versionRange = "[21,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    versionRange = "[1.21.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "etcetera"
    versionRange = "[2.2.0-neoforge,)"
    ordering = "NONE"
    side = "BOTH"
